services:
  mongo:
    image: mongo:7
    container_name: noxstock-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - noxstock-mongo-data:/data/db

volumes:
  noxstock-mongo-data:
